package(default_visibility = ["//visibility:public"])

load("/tools/build_defs/jsonlang_dev/jsonlang_docs", "jsonlang_docs_srcs_zip")

jsonlang_docs_srcs_zip(
    name = "jsonlang_docs_srcs",
    srcs = [
        "bar_menu.1.jsonlang",
        "bar_menu.1.jsonlang.golden",
        "bar_menu.2.jsonlang",
        "bar_menu.2.jsonlang.golden",
        "bar_menu.3.jsonlang",
        "bar_menu.3.jsonlang.golden",
        "bar_menu.5.jsonlang",
        "bar_menu.5.jsonlang.golden",
        "bar_menu.6.jsonlang",
        "bar_menu_utils.libjsonlang",
        "bar_menu.7.jsonlang",
        "bar_menu.7.jsonlang.golden",
        "bar_menu.8.jsonlang",
        "bar_menu.8.jsonlang.golden",
        "bar_menu.9.jsonlang",
        "bar_menu.9.jsonlang.golden",
        "bar_menu.10.jsonlang",
        "bar_menu.10.jsonlang.golden",
        "bar_menu.11.jsonlang",
        "bar_menu.11.jsonlang.golden",
        "build_example.jsonlang",
        "example_operators.jsonlang",
        "example_operators.jsonlang.golden",
        "hidden_fields.jsonlang",
        "hidden_fields.jsonlang.golden",
        "landingpage.jsonlang",
        "landingpage.jsonlang.golden",
        "martinis.libjsonlang",
        "no_ingredients.jsonlang",
        "no_ingredients.jsonlang.error",
    ],
)
